### PR TITLE
Hypocycloid

### PR DESCRIPTION
**Pull request by bevinhex**
Hi, thanks for the great work you put in, I found some time to contribute a bit, here is hypocycloid gear with its pins, there are two extra options:

show_pins
show_opposite_cam

which shows extra disk and pins if needed, algorithm is from http://www.zincland.com/hypocycloid/
Was using some python generated from the site for my project, thought adding it to your library directly is logical choice

### CODE REVIEW

**Comment by looooo** [comment]
thanks @bevinhex this looks good.

some things I came across:
- for show_opposite_cam = False and show_pins = False there is an error reported:
```
<Exception> Multi fuse failed
```
- It would be nice to use bsplines to interpolate the points of one tooth and then rotate the geometry and create the full wire
- please use lower_case variabes where possible.
- if possible height=0 should return the wire and not an error

We can also work on this after merging this PR.

**Comment by bevinhex** [comment]
Thanks for the feedback @looooo , my bad, I was eager to get it done quickly, didn't consider too much error checks, not my usual style, I'll get into those mentioned above and push fixes ASAP.

**Comment by bevinhex** [comment]
@looooo I fixed the bugs and did some optimization, about the b-spline, I'm not sure how yet, so please test and merge this one first, at least we will have a working version, I will get to b-spline later.

**Comment by looooo** [comment]
thanks

**Comment by looooo** [comment]
I added the bspline interpolation and refactored the functions a little bit. Maybe you can have a look and test if everything works as expected: 
https://github.com/looooo/freecad.gears/commit/081aa5fcea98b6eb2564403f446749453fbd9a33

**Comment by bevinhex** [comment]
Checked the commit, looks awesome, sorry about the uppercase functions, when you said 'lower case variables' , didn't thought of functions.
Thanks for fixing those.

**Pull request merged**
